#! /bin/bash

#set -m to set job control
#set -m

fastfetch --os-file   $HOME/Projects/LinuxAppBox/GuestSystemFiles/${1}

#commented out fastfetch as it' shouldn't be reqiered it should be optional

distrobox-enter $1 -e 'cd $HOME'


#$SHELL
